# ==============================================================================
# SETTINGS FILE (toml format): Leave a space before and after the "=" (e.g. name = "value"). Strings need "", numbers don't. Allows for scientific notation (e.g. num = 4e-12) and simple math operations (*/+-^) in strings as described in settings.py (e.g. num = "-1e4 ^ 2e-3")
# ==============================================================================


# ==============================================================================
# important settings:
# ==============================================================================


# ==============================================================================
# less important settings:
# ==============================================================================







